-- The order is intentional
require("config.options")
require("config.editor.colorscheme")
require("config.editor.snacks")
require("config.editor.auto-save")
require("config.editor.bufferline")
require("config.editor.gitsigns")
require("config.editor.guess-indent")
require("config.editor.lualine")
require("config.editor.noice")
require("config.editor.nvim-autopairs")
require("config.editor.treesitter")
require("config.editor.smartyank")
require("config.completion")
